# Copyright 2022 Practically.io All rights reserved
#
# Use of this source is governed by a BSD-style
# licence that can be found in the LICENCE file or at
# https://www.practically.io/copyright/

git:
  provider: github
  project: AdeAttwood/Runner

hooks:
  commit-msg:
    - conventional-tools commitlint
  pre-push:
    - conventional-tools commitlint -l1
  prepare-commit-msg:
    - |
      # Commitgen
      if [ -z "${2}" ]; then
          echo "$(conventional-tools commitgen)$(cat ${1})" > ${1};
      fi
  pre-commit:
    - run lint:go
    - run lint:jsonnet
